name: PhysicEnderPearl
version: '1.0.1'
main: com.NguyenDevs.physicEnderPearl.PhysicEnderPearl
api-version: '1.19'
commands:
  physicenderpearl:
    description: PhysicEnderPearl Manage
    usage: /<command> [reload]
    aliases: [pep]
permissions:
  pep.use:
    description: Allow to use physic enderpearl logic
    default: true
  pep.reload:
    description: Reload plugin
    default: op