name: PhysicEnderPearl
version: '1.0.0'
main: com.NguyenDevs.physicEnderPearl.PhysicEnderPearl
api-version: '1.21'
commands:
  physicenderpearl:
    description: PhysicEnderPearl Manage
    usage: /<command> [reload]
permissions:
  physicenderpearl.enabled:
    description: Allow to use physic enderpearl logic
    default: true
  physicenderpearl.reload:
    description: Reload plugin
    default: op